server:
  port : 8080
  servlet:
    context-path: /api/dts
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/dts"
    username: root
    password: root
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: none
jwt:
  signerKey: "z+7kjfwfgxuzW2+1/EVCduqLWkVwR/atuCqg+EtTogGK5RdioGkeSeY3Mfyps89G"
  valid-duration: 36000
  refreshable-duration: 36000

